# Generated by Django 2.2.28 on 2023-02-21 11:02

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230220_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hex_color_code',
            field=models.CharField(default=0, max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code', regex=re.compile('^#[0-9A-F]{6}$'))], verbose_name='цветовой HEX-код'),
            preserve_default=False,
        ),
    ]
