# Generated by Django 2.2.28 on 2023-02-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_tag_hex_color_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hex_color_code',
            new_name='color',
        ),
    ]
