# Generated by Django 2.2.28 on 2023-02-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230221_1710'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='name_unit_of_measurement_unique',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit_of_measurement',
            new_name='measurement_unit',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='name_measurement_unit_unique'),
        ),
    ]
