# Generated by Django 2.2.28 on 2023-02-26 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interactions_with_recipes', '0002_shoppinglist_recipe'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='shopping_list',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь'
            ),
        ),
        migrations.AddField(
            model_name='favorites',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='recipes.Recipe', verbose_name='рецепт'
            ),
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorite_list',
                to=settings.AUTH_USER_MODEL,
                verbose_name='пользователь'
            ),
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'),
                name='favorites_user_recipe_unique'
            ),
        ),
    ]
