# Generated by Django 2.2.28 on 2023-02-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions_with_recipes', '0003_auto_20230226_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='liked_users',
                to='recipes.Recipe', verbose_name='рецепт'
            ),
        ),
    ]
