# Generated by Django 2.2.28 on 2023-02-28 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20230227_1409'),
        ('interactions_with_recipes', '0004_auto_20230227_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'),
                name='shoppinglist_user_recipe_unique'
            ),
        ),
    ]
